name: flutter_keyboard_visibility_web
description: An implementation for the web platform of `flutter_keyboard_visibility'
version: 2.1.0
homepage: https://github.com/MisterJimson/flutter_keyboard_visibility
repository: https://github.com/MisterJimson/flutter_keyboard_visibility

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.20.0"

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterKeyboardVisibilityPlugin
        fileName: flutter_keyboard_visibility_web.dart

dependencies:
  flutter_keyboard_visibility_platform_interface: ^2.0.0
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  web: ">=0.5.1 <2.0.0"

dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter
